version: "3.4"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
